-- Insertando algunos registros para que la BBDD no esté vacía

INSERT INTO USUARIOS (ID,USER_NAME,USER_PWD,ID_PSIC) VALUES (10001,'Claudia','password1',20001);
INSERT INTO USUARIOS (ID,USER_NAME,USER_PWD,ID_PSIC) VALUES (10002,'Serena','password2',0);
INSERT INTO USUARIOS (ID,USER_NAME,USER_PWD,ID_PSIC) VALUES (10003,'Maria','password3',20002);
INSERT INTO USUARIOS (ID,USER_NAME,USER_PWD,ID_PSIC) VALUES (10004,'Alicia','password4',20001);
INSERT INTO USUARIOS (ID,USER_NAME,USER_PWD,ID_PSIC) VALUES (10005,'Pepe','password5',0);
INSERT INTO USUARIOS (ID,USER_NAME,USER_PWD,ID_PSIC) VALUES (10006,'Fernando','password6',20002);

INSERT INTO PSICOLOGOS (ID,PSIC_NAME,PSIC_PWD,EMPLOYER_ID) VALUES (20001,'Marina','password4',30001);
INSERT INTO PSICOLOGOS (ID,PSIC_NAME,PSIC_PWD,EMPLOYER_ID) VALUES (20002,'Carla','password5',0);
INSERT INTO PSICOLOGOS (ID,PSIC_NAME,PSIC_PWD,EMPLOYER_ID) VALUES (20003,'CarlaBorrar','password5',0);
INSERT INTO PSICOLOGOS (ID,PSIC_NAME,PSIC_PWD,EMPLOYER_ID) VALUES (20004,'MarinaBorrar','password4',30002);
INSERT INTO PSICOLOGOS (ID,PSIC_NAME,PSIC_PWD,EMPLOYER_ID) VALUES (20005,'Pedro','password4',30002);

INSERT INTO CENTROS(EMPLOYER_ID,EMPLOYER_NAME,POSTAL_CODE) VALUES (30001,'Centro de Salud de Vva del Pardillo',28229);
INSERT INTO CENTROS(EMPLOYER_ID,EMPLOYER_NAME,POSTAL_CODE) VALUES (30002,'Centro de Salud de Majadahonda',28220);